version: "3.1"

services:
  mongodb:
    image: mongo
    volumes: 
      - db:/data/db

  todo:
    build: .
    command: ["npm", "start"]
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 8000:8000
      - 5858:5858
    environment:
      - LISTEN_ADDRESS=0.0.0.0
      - LISTEN_PORT=8000
      - NODE_ENV=development

volumes:
  db:
