version: "3.1"

services:
  mongodb:
    image: mongo
    volumes: 
      - db:/data/db
    networks:
      - all

  todo:
    build: .
    command: ["npm", "start"]
    volumes:
      - .:/home/app
      - node_modules:/home/app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - all
    environment:
      - LISTEN_ADDRESS=0.0.0.0
      - LISTEN_PORT=8000
      - NODE_ENV=development

volumes:
  db:
  node_modules:

networks:
  all:
